name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: |
          npm ci
      - name: Verify code is formatted correctly
        run: |
          npx prettier --check .
      - name: Lint
        run: |
          npm run lint
      - name: Build
        run: |
          npm run build
      - name: Coverage
        run: |
          npm test
