name: SKY UX CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - '*.*.*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: blackbaud/skyux-sdk-actions@remove-browserstack
        with:
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          project: 'docs-tools'
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          hook-after-build-public-library-success: ./scripts/after-build-public-library-success.js
          code-coverage-browser-set: speedy
          code-coverage-threshold-branches: 90
          code-coverage-threshold-functions: 92
          code-coverage-threshold-lines: 92
          code-coverage-threshold-statements: 93
      - name: Upload coverage report
        run: bash <(curl -s https://codecov.io/bash)
